### ISSUE TITLE
Feature request: parsing textStyle and other custom tags in Line's metadata

### ISSUE THREAD

**Issue by LvanWissen** [knaw-huc/pagexml#10]
The metadata that is parsed by the pagexml-tools is limited to `readingOrder` and `structure` tags, while PageXML file can also contain `textStyle` and other custom attributes (e.g. `place`, `date` and other entity tags).

Example for a single occurrence of `textStyle`:
```XML
<TextLine id="r2l10" custom="readingOrder {index:9;} textStyle {offset:1; length:1;superscript:true;}">
```

Example for multiple occurrences of `textStyle`:
```XML
<TextLine id="r2l11" custom="readingOrder {index:10;} textStyle {offset:13; length:1;superscript:true;} textStyle {offset:20; length:1;superscript:true;}">
```

Example for entity tags `place` and `date`:
```XML
<TextLine id="tr_1_tl_6" custom="readingOrder {index:2;} place {offset:0; length:11;}">

<TextLine id="tr_1_tl_5" custom="readingOrder {index:1;} date {offset:0; length:9;}">
```

I propose adding two extra fields to the metadata:

1. `text_style` for those `textStyle` elements. The value of this element in the metadata dict is always a list, since this attribute can have multiple occurrences.
2. `custom_tags` for other attributes that can be specified by the user. This value is also a list, but usually empty.

I can do a PR (see a quick-and-dirty implementation: https://github.com/LvanWissen/pagexml/commit/298aba3af6e1c2a350731de840644cf6a4c514e3), but this for sure is not the most efficient solution. Ideally, those custom tags are accessible on a higher level than the TextLine, including some nifty textual extraction of the included offset and length attributes, but that may require some refactoring...

**Comment by brambg** [comment]
I've merged the PR, we will think about a more efficient solution.

**Comment by LvanWissen** [comment]
Thanks for merging https://github.com/knaw-huc/pagexml/pull/11!

I'll close this issue with a bit of documentation on how I used the [helper function](https://pagexml.readthedocs.io/en/latest/source/api/pagexml.helper.pagexml_helper.html#pagexml.helper.pagexml_helper.get_custom_tags) that was added. For future reference:

```python
from pagexml.parser import parse_pagexml_file
from pagexml.helper.pagexml_helper import get_custom_tags

filepath = "example/urn-gvn-EVDO01-IIAV002_IAV001000030-large_03.xml"
page = parse_pagexml_file(filepath, custom_tags=("place", "date"))

annotations = []

tags = get_custom_tags(page)

for n, tag in enumerate(tags, 1):
    annotation = {
        "@context": "http://www.w3.org/ns/anno.jsonld",
        "id": "#" + str(n),
        "type": "Annotation",
        "body": [
            {
                "type": "TextualBody",
                "value": tag["type"],
                "purpose": "classifying",
            }
        ],
        "target": {
            "type": "SpecificResource",
            "source": tag["line_id"],
            "selector": [
                {
                    "type": "TextQuoteSelector",
                    "exact": tag["value"],
                },
                {
                    "type": "TextPositionSelector",
                    "start": tag["offset"],
                    "end": tag["offset"] + tag["length"],
                },
            ],
        },
    }

    annotations.append(annotation)
```
