### ISSUE TITLE
Update Pandas dependency

### ISSUE THREAD

**Issue by carschno** [knaw-huc/pagexml#13]
The current version depends on pandas version `^1.5.3` which implies `<2.0`.
As a result, every project that uses Pandas >= 2.0 will not be able to use `pagexml`.

Unless there are reasons to enforce Pandas < 2.0, the simplest solution would be to allow for Pandas 2.0 and relax the version constraint to `>=1.5.3 <3.0.0`.

**Comment by brambg** [comment]
Thanks, this should be fixed in the latest version: 0.4.1
